### ISSUE TITLE
Theme sometimes not loaded

### ISSUE THREAD

**Issue by Tychodewaard** [nbrightproject/NBrightBuy#137]
I have a bespoke theme but once or twice a day, it is not loaded. If I empty the cache, everything is fine again. 
Strangly, this happens only on 2 portals within a 13 portal multistore set up.

1. The main store. This is just 1 language but has about 2500 products
2. A sub store that has 5 languages but only 10 products.

Other sub portals with more products and/or languages don't have this problem. 

The shop is 3.6.6
Unfortunately, I don't have an exact path to reproduce.
What I do have is the theme as intended and the theme that is loaded when the bespoke theme is not loaded.

[source alternatief as intended.txt](https://github.com/nbrightproject/NBrightBuy/files/1426807/source.alternatief.as.intended.txt)
[source alternatief when theme not loaded.txt](https://github.com/nbrightproject/NBrightBuy/files/1426808/source.alternatief.when.theme.not.loaded.txt)

**Comment by leedavi** [comment]
Are their any portals in that install that does use "ClassicRazor"?

**Comment by Tychodewaard** [comment]
@leedavi , I sent you a link to a xls with an entire overview of all pages and module settings.

**Comment by Tychodewaard** [comment]
Yesterday I saw this error. Might that have something to do with it?

IO.IOException: The process cannot access the file 'C:\Inetpub\vhosts\alternatief.com\httpdocs\Portals\tjeps005l\NBSTemp\hDiYJX1MEHxZ' because it is being used by another process. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access) at NBrightCore.common.Utils.SaveFile(String fullFileName, Byte[] buffer) at NBrightCore.common.Utils.SaveFile(String fullFileName, String data) at Nevoweb.DNN.NBrightBuy.Components.NavigationData.Save() in D:\Websites\dev\dev-802\files\DesktopModules\NBright\NBrightBuy\Components\NavigationData.cs:line 403 at Nevoweb.DNN.NBrightBuy.Components.NavigationData.ResetSearch() in D:\Websites\dev\dev-802\files\DesktopModules\NBright\NBrightBuy\Components\NavigationData.cs:line 488 at Nevoweb.DNN.NBrightBuy.ProductRazorView.RazorPageLoad() in D:\Websites\dev\dev-802\files\DesktopModules\NBright\NBrightBuy\ProductRazorView.ascx.cs:line 326 at Nevoweb.DNN.NBrightBuy.ProductRazorView.OnLoad(EventArgs e) in D:\Websites\dev\dev-802\files\DesktopModules\NBright\NBrightBuy\ProductRazorView.ascx.cs:line 179

**Comment by leedavi** [comment]
Where do you find this error.  I doubt it's the cause, this can happen, but should be isolated and not reported.

**Comment by Tychodewaard** [comment]
It was in the event log. Now not anymore (only keeps x events...) 
But this time a new error (maybe again nothing?):

Message:Illegal characters in path.
StackTrace:
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Web.InternalSecurityPermissions.PathDiscovery(String path)
   at System.Web.HttpRequest.MapPath(VirtualPath virtualPath, VirtualPath baseVirtualDir, Boolean allowCrossAppMapping)
   at System.Web.HttpServerUtility.MapPath(String path)
   at Nevoweb.DNN.NBrightBuy.XmlConnector.ProcessRequest(HttpContext context) in D:\Websites\dev\dev-802\files\DesktopModules\NBright\NBrightBuy\XmlConnector.ashx.cs:line 197
