### ISSUE TITLE
Installation issues with new store

### ISSUE THREAD

**Issue by chrissieq** [nbrightproject/NBrightBuy#4]
Hi Dave

Looking in the Event Viewer, this is one of the page load exception error messages. If it will make things easier, I can add a super user account for you?

Kind regards
Christine

AbsoluteURL:/bapsh/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:a6d2e40c-278b-4159-bae8-1cd5f44e09ef
AssemblyVersion:7.4.1
PortalId:0
UserId:1
TabId:198
RawUrl:/bapsh/Admin/NBSBackOffice.aspx
Referrer:http://bapsh.qsdesigns.co.uk/bapsh/Admin/Pages.aspx
UserAgent:Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)
ExceptionHash:pRCrRYkIOWxH979QCxxevA==
Message:Object reference not set to an instance of an object.
StackTrace:

InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at Nevoweb.DNN.NBrightBuy.Components.PluginData.GetPluginList()
   at Nevoweb.DNN.NBrightBuy.Components.PluginData.GetProviders(String providerType, Boolean activeOnly)
   at Nevoweb.DNN.NBrightBuy.Base.NBrightBuyBase.OnInit(EventArgs e)
   at Nevoweb.DNN.NBrightBuy.Admin.BackOffice.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by leedavi** [comment]
Odd, it's seems to be looking for a plugin that doesn't exists.  I've not seen this before.  Can you send me a host login to nevoweb and I'll see if I can understand why.

**Comment by chrissieq** [comment]
Can you let me have the email address?

**Comment by leedavi** [comment]
dcl @ nevoweb .com

**Comment by chrissieq** [comment]
URL – http://bapsh.qsdesigns.co.uk/bapsh

**Comment by leedavi** [comment]
OK, this looks like the correct config files needed to run NBS have not been created on the file system.

Have you got a enhanced file security on your hosting server that prevents these from being created?

I've tried a couple of things, but doesn't work.  But it really needs the security setting of the server checking.

**Comment by chrissieq** [comment]
Right o. I will check the security settings and let you know what’s happening

Many thanks for your help

Kind regards

Christine

**Comment by chrissieq** [comment]
Some progress!

I have 2 hosting accounts – 1 shared hosting and 1 virtual server. It seems to be the virtual server that is giving the trouble as on my shared hosting account, everything installs correctly. I will do some more investigating as it must be a setting on the virtual server that I’ve missed

Kind regards

Christine

**Comment by chrissieq** [comment]
Update – success :)

This was weird, but down to a combination of the way in which my virtual server is set up and not installing DNN into the root – I recreated the site from scratch and I’m now good to go!

Many thanks for your help

Kind regards

Christine

**Comment by ghbn1362** [comment]
I install in DNN 7.4.2 and 8 / 8.1 / 8.2 in localhost with full access but get this error

[ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.NullReferenceException: Object reference not set to an instance of an object.
   at Nevoweb.DNN.NBrightBuy.Components.PluginData.GetProviders(String providerType, Boolean activeOnly)
   at Nevoweb.DNN.NBrightBuy.Base.NBrightBuyBase.OnInit(EventArgs e)
   at Nevoweb.DNN.NBrightBuy.Base.NBrightBuyFrontOfficeBase.OnInit(EventArgs e)
   at Nevoweb.DNN.NBrightBuy.ProductView.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at DotNetNuke.UI.Containers.Container.get_ModuleControl()
   at DotNetNuke.UI.Containers.Container.ProcessModule()
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)

I test NBRight
version 03.01.02
version 03.01.08
version 03.01.09
version 03.01.14

and get this error

**Comment by leedavi** [comment]
HI, your not giving me any information to work with, I'll need to know what you did in what order and at what point it went wrong.

Did you follow these instructions:  http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/Installation.aspx
