### ISSUE TITLE
/Admin/NBS-Back-Office : 500 - Internal server error

### ISSUE THREAD

**Issue by Feng155** [nbrightproject/NBrightBuy#81]
I got this error after  I installed and go to /Admin/NBS-Back-Office : 
- 500 - Internal server error
- There is a problem with the resource you are looking for, and it cannot be displayed.

Who can help me out? Thanks!

**Comment by leedavi** [comment]
Have you got any error message in the DNN event log?

**Comment by Feng155** [comment]
Yes: "There is a problem with the resource you are looking for, and it cannot be displayed." 

In the Event Viewer:

AbsoluteURL:/b/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:3ff5292e-a154-4229-9a57-0f9fe2a64721
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:AbxYA63FKtF1HA6j58dY/Q==
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at Nevoweb.DNN.NBrightBuy.Components.PluginData.GetProviders(String providerType, Boolean activeOnly)
   at Nevoweb.DNN.NBrightBuy.Base.NBrightBuyBase.OnInit(EventArgs e)
   at Nevoweb.DNN.NBrightBuy.Admin.BackOffice.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: WIN-XXXXXXXXX

**Comment by Feng155** [comment]
I'm using DNN 8.0.4

**Comment by leedavi** [comment]
I think this might be from where the BO settings which are saved in cookie and the data saved in there is no longer valid.  

Try clearing you cookies and try a different browser and see if that works.

**Comment by Feng155** [comment]
Tried 4 times, no good. I've decided not to use this testing version module.

**Comment by leedavi** [comment]
I'm not sure what version your using, but try a fresh install with the latest version on DNN Store. that should be OK.

**Comment by leedavi** [comment]
Oh, One other thought, make sure you have the latest template system, it could be your trying to use an old version of the template system with a NBrightBuy module that's not compatible.

**Comment by Feng155** [comment]
I had even no chance to get in the BO page or settings. Right after I
installed, click on this page, it shows this error message.
Server Error
500 - Internal server error.There is a problem with the resource you are
looking for, and it cannot be displayed.

In Event Viewer:
Date
Log Type
Username
Website
Summary
[image: pasted1]
10/26/2016 10:29:02 AM
Page Load Exception
host
xxxx

AbsoluteURL /b/Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataPro

_AbsoluteURL_:/b/Default.aspx

_DefaultDataProvider_:DotNetNuke.Data.SqlDataProvider, DotNetNuke

_ExceptionGUID_:1df65cad-5543-44f8-9265-1772bc026241

_AssemblyVersion:_

_PortalId:_-1

_UserId:_-1

_TabId:_-1

_RawUrl:_

_Referrer:_

_UserAgent:_

_ExceptionHash:_AbxYA63FKtF1HA6j58dY/Q==

_Message:_Object reference not set to an instance of an object.

_StackTrace:_

_InnerMessage:_Object reference not set to an instance of an object.

_InnerStackTrace:_

   at Nevoweb.DNN.NBrightBuy.Components.PluginData.GetProviders(String
providerType, Boolean activeOnly)
   at Nevoweb.DNN.NBrightBuy.Base.NBrightBuyBase.OnInit(EventArgs e)
   at Nevoweb.DNN.NBrightBuy.Admin.BackOffice.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean
includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

_Source:_

_FileName:_

_FileLineNumber:_0

_FileColumnNumber:_0

_Method:_

_Server Name_: WIN-xxxxxxxxxxx

David Lee notifications@github.com 於 2016年10月26日 週三 上午2:22寫道：

**Comment by leedavi** [comment]
Try going into the DNN install packages and install the latest Template system, you can download it from the DNN Store.  That might solve it.

**Comment by Feng155** [comment]
Thanks David. Have you tried it on DNN 8.0.4 the latest version?

**Comment by micahsdad1402** [comment]
I'm running fine on 8.04
